<?php

function text_recognizer_menu() {
    $items['text-recognizer'] = array(
        'title' => 'Get text from screenshot',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('text_recognizer_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['text-recognizer-image-uploaded'] = array(
        'title' => 'Your Image',
        'page callback' => 'text_recognizer_image_uploaded',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK
    );
    return $items;
}

function text_recognizer_form() {
    $form['image_upload'] = array(
    '#type' => 'managed_file',
    '#name' => 'image_upload',
    '#title' => t('Get text from screenshot'),
    '#size' => 40,
    '#description' => t("Higher resolution images with black font on a light background are most likely to work."),
    '#upload_location' => 'public://'
  );
  $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Go',
    );
  return $form;
}

function text_recognizer_form_submit($form, &$form_state) {
  if (isset($form_state['values']['image_upload'])) {
    $file = file_load($form_state['values']['image_upload']);


    $_SESSION['image_upload'] = $file;
    $form_state['redirect'] = 'text-recognizer-image-uploaded';
  }
}

function text_recognizer_image_uploaded() {
    $image_upload = $_SESSION['image_upload'];
    drupal_add_js(drupal_get_path('module', 'text_recognizer') . '/js/draw_image.js');
    drupal_add_js(drupal_get_path('module', 'text_recognizer') . '/js/text_recognizer.js');

    return '<img id="uploaded-image" src="sites/default/files/' . $image_upload->filename . '"><br>' . '<button id="draw_button">Draw</button>' . '<button id="execute_button">Execute</button>' . '<h4><strong>Your image text goes here:</strong></h4> <div id="translation"></div><br>' . '<canvas id="image-canvas" width="800" height="800"></canvas>';
}
