<?php

function text_recognizer_menu() {
    $items['text-recognizer'] = array(
        'title' => 'Get text from screenshot',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('text_recognizer_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['text-recognizer-image-uploaded'] = array(
        'title' => 'Your Image',
        'page callback' => 'text_recognizer_image_uploaded',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK
    );
    return $items;
}

function text_recognizer_form() {
    $form['image_upload'] = array(
    '#type' => 'managed_file',
    '#name' => 'image_upload',
    '#title' => t('Your image'),
    '#size' => 800,
    '#description' => t("blah blah blah blah blah."),
    '#upload_location' => 'public://'
  );
  $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Go',
    );
  return $form;
}

function text_recognizer_form_submit($form, &$form_state) {
  if (isset($form_state['values']['image_upload'])) {
    $file = file_load($form_state['values']['image_upload']);


    // $img_div = DOMDocument::getElementById ('edit-image-upload-upload');
    // $img_anchors = $img_div->getElementsByTagName('a');
    // $img_anchor = $img_anchors[0];
    // $img_src = $img_anchor->getAttribute('src');
    //
    $_SESSION['image_upload'] = $file;
    $form_state['redirect'] = 'text-recognizer-image-uploaded';
    // $file->status = FILE_STATUS_PERMANENT;
    //
    // file_save($file);
  }
}

function text_recognizer_image_uploaded() {
    $image_upload = $_SESSION['image_upload'];
    drupal_add_js(drupal_get_path('module', 'text_recognizer') . '/js/draw_image.js');
    // var_dump(get_object_vars($image_upload));

    return 'LEZ GO ' . '<img id="uploaded-image" src="sites/default/files/' . $image_upload->filename . '">' . '<button id="draw_button">Draw</button>' . '<canvas id="image-canvas" width="500" height="500"></canvas>';
}
